trigger:
  branches:
    include:
    - '*'

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'Sonarqube_Brainvire_Inhouse_server'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'NodeJS-Base-Structure-sonarqube'

# Run Code Analysis task
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

# Publish Quality Gate Result task
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'