const TAG_CONFIG = {
  html: "",
  allowedClasses: {
    "*": [
      "cta-banner",
      "cta-banner-1",
      "cta-banner-2",
      "cta-banner-3",
      "cta-banner-4",
      "container",
      "cta-banner-block",
      "d-flex",
      "d-flex-row",
      "d-align-center",
      "d-just-between",
      "cta-banner-left-block",
      "cta-banner-left",
      "cta-artical-banner",
      "cta-artical-banner-left",
      "cta-artical-banner-right",
      "h5",
      "h6",
      "Imgdiv",
      "btn-secondary",
      "btn",
      "cta-banner-right",
    ],
  },
  allowedTags: [
    "html",
    "head",
    "title",
    "body",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "p",
    "a",
    "ul",
    "ol",
    "nl",
    "li",
    "b",
    "i",
    "strong",
    "em",
    "strike",
    "abbr",
    "code",
    "hr",
    "br",
    "div",
    "table",
    "thead",
    "caption",
    "tbody",
    "tfoot",
    "col",
    "colgroup",
    "tr",
    "th",
    "td",
    "pre",
    "iframe",
    "img",
    "map",
    "area",
    "canvas",
    "figcaption",
    "figure",
    "picture",
    "svg",
    "video",
    "source",
    "audio",
    "track",
    "link",
    "nav",
    "span",
    "abbr",
    "address",
    "del",
    "dfn",
    "em",
    "q",
    "small",
    "sub",
    "sup",
    "dl",
    "dt",
    "dd",
    "section",
  ],

  allowedStyles: {
    "*": {
      color: [/^#(0x)?[0-9a-f]+$/i, /^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/],
      "font-size": [/^\d+(?:px|em|%)$/],
      "font-family": [/^[a-zA-Z]+$/],
    },
  },
  allowedAttributes: {
    "*": [
      "id",
      "href",
      "align",
      "alt",
      "center",
      "bgcolor",
      "style",
      "height",
      "width",
      "title",
      "target",
      "rel",
      "src",
      "lang",
      "html",
      "class",
    ],
  },
  selfClosing: ["img", "br", "hr", "area", "base", "basefont", "input", "link", "meta"],
};

export default TAG_CONFIG;
