import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import APPCONFIG from "@/config/app.config";
import { ToastContainer, toast } from "react-toastify";
import { loadStripe } from "@stripe/stripe-js";
import http from "@/axios/axios";

export default function Home() {
  const cartAmount = 200;
  const placeOrder = async () => {
    if (cartAmount > APPCONFIG.STRIPE_MAXIMUM_AMOUNT_ACCEPT) {
      toast.error(
        `Maximum transaction amount is less then ₹ ${APPCONFIG.STRIPE_MAXIMUM_AMOUNT_ACCEPT?.toLocaleString(
          APPCONFIG.NUMBER_FORMAT_LANG
        )}`,
        {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
        }
      );
      return;
    }

    let obj = {
      unit_amount: cartAmount * 100,
      currency: "INR",
      name: "Indian Army Logo",
      quantity: 1,
      description: "Best Place to buy Online Images",
      customer_email: "akash.sanariya@brainvire.com",
      order_id: "1",
      success_url: window ? window.location.origin : "",
      cancel_url: window ? window.location.origin : "",
      //   success_url: "http://localhost:3000" + "/cart/checkout_list/",
      //   cancel_url: "http://localhost:3000" + "/cart/checkout_list/",
    };

    const stripe = await loadStripe(APPCONFIG?.STRIPE_PUBLIC_KEY);
    const checkoutSession: any = await http.post(
      "/api/create-stripe-session/",
      {
        item: obj,
      }
    );
    if (checkoutSession?.error?.raw?.message) {
      toast.error(checkoutSession?.error?.raw?.message, {
        position: "top-right",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: "light",
      });
      return;
    }
    if (stripe) {
      const result = await stripe.redirectToCheckout({
        sessionId: checkoutSession?.data?.id,
      });
      if (result.error) {
        toast.error(result.error.message, {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: "light",
        });
      }
    }
  };

  return (
    <>
      <Head>
        <title>Next Js Stripe App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer />
      <main className={styles.main}>
        <div className={styles.card}>
          <Image
            width={50}
            height={50}
            alt="Indian Army Logo"
            src={"/indian.jpg"}
          />
          <h1>Indian Army</h1>
          <p className={styles.price}>₹ {cartAmount}</p>
          <p>
            Indian Army exists with values such as Spirit of Selfless Sacrifice,
            Valour, Discipline and Integrity. The Logo of the Indian Army
            depicts two swords in cross below the National Emblem of India. The
            National Emblem and swords are in the yellow shade with the
            background in the shade of red.
          </p>
          <p>
            <button onClick={placeOrder}>Buy Now</button>
          </p>
        </div>
      </main>
    </>
  );
}
