export const SignInActionTypes = {
  INITIATE_ADD_DATA: "INITIATE_ADD_DATA",
  ADD_SIGNIN_DATA_SUCCESS: "ADD_SIGNIN_DATA_SUCCESS",
  ADD_SIGNIN_DATA_FAIL: "ADD_SIGNIN_DATA_FAIL",
  UPDATE_SIGNIN_DATA_SUCCESS: "UPDATE_SIGNIN_DATA_SUCCESS",
  CART_COUNT:"CART_COUNT",
  WISH_LIST_COUNT:"WISH_LIST_COUNT",
  REVIEW_COUNT:"REVIEW_COUNT",
  OTP_VERIFICATION : "OTP_VERIFICATION"
};
