//  Common ENUM

export const CommonMaster = {
    GENERAL_MASTER: 'General Masters',
    METAL_MASTER: 'Metal Masters',
    CAREER_MASTER: 'Career Masters',
    CATALOGUE: "Catalogue Management",
    PRODUCT_REVIEW: 'Product Review',
    RETURN_REASONS: 'Return Reasons',
    GENDER: 'Gender',
    PRODUCT_TAG: 'Product Tag',
    PRODUCT_TAG_IMAGE: "Product Tag Image",
    FAQ: 'FAQ',
    CMS: 'CMS Pages',
    GROUP_MASTER: 'Group Master',
    CONTACT_US: "Contact Inquiries",
    HCP_INQUIRIES: "HCP Inquiries",
    PRESCRIBED_PRODUCTS: "Prescribed Products",
    SUBSCRIBE: "Newsletter Subscribers",
    SETUP_YOUR_SITE:' Setup Your Site',
    REQUESTS: 'Requests',
    SYSTEM_EMAIL: 'System Emails',
    PRODUCT_PRICES: "Products & Prices",
    PRODUCT_IMPORT_HISTORY: "Product Import History",
    PRODUCT_SYNC_HISTORY: "Product Sync History",
    BANGLE_MASTER: 'Bangle Master',
    SOCIAL: 'Social Links',
    QUICK_LINKS: "Quick Links",
    TITLE_CONFIG: "Title Configuration",
    GENERAL_CONFIGURATION: 'General Configuration',
    CONTACT_US_CONFIGRATION: 'Contact Us Configurations',
    HOME_CONFIGRATION: 'Home Configurations',
    FOOTER_CONFIGURATION: 'Footer Configuration',
    LOCALIZATION: 'Localization',
    COUNTRY: 'Country',
    STATE: 'State',
    CITY: 'City',
    SETTING: 'Setting',
    SETTINGS: 'Settings',
    CONTACTADDRESS: 'Contact Addresses',
    CATEGORY_MANAGEMENT: 'Category Master',
    CATEGORY: 'Category',
    CATEGORY_TYPE: 'Category Type',
    SUB_CATEGORY: 'Sub Category',
    CATEGORY_GROUP_MANAGEMENT: "Category Management",
    CATEGORY_SEQUENCE: "Category Sequence",
    FILTER_SEQUENCE: 'Filter Sequence',
    HCP: "HCP Management",
    PATIENTS: "Patients",
    ORDERS: "Orders",
    TRANSACTIONS: "Transactions",
    COMMISSION_REPORTS: "Commission Reports",
    BANNER: 'Banner',
    USER_MANAGEMENT: "Patient Management",
    ADMIN_USERS: 'Admin Users',
    B2B_USERS: 'B2B Users',
    MICROSITE_ADMIN_USERS: 'Microsite Admin Users',
    B2B2C_USERS: "HCP Patients",
    ROLE_PERMISSION: 'Roles and Permission',
    ACCOUNT_ADDRESS: 'Account Address',
    PRODUCT: 'Product',
    PRODUCT_MASTER: "Product Master",
    SUMMARY: 'Summary',
    WISHLIST_ITEM: 'Wishlist Items',
    CART: 'Cart',
    CART_ITEM: 'Cart Items',
    SLUG_MASTER: 'Slug Master',
    TAX_RATE: "Tax Rates",
    REPORT: 'Report',
    REPORTS: 'Reports',
    OTHER_CONFIGURATION: 'Other Configuration',
    LOGIN_REPORT: 'Login Report',
    CAREER_APPLICATION_DETAILS: "Career Application Details",
    METAL_RATE: "Metal",
    DIAMOND_RATE: 'Diamond',
    COLOR_STONE_RATE: 'Color Stone',
    LABOUR_CHARGE_RATE: "Labour Charge",
    WEB_CONFIG: "Web Config",
    MASTERS: "Masters",
    USER_AREA: "User Area",
    PRODUCT_CONFIGURATION: 'Common Configurations',
    NUMBER_GENERATOR: 'Number Generator',
    PINCODE: 'Pincode',
    ABOUT_US_CONFIG: 'About Us Config',
    ABOUT_US: 'About Us',
    HCP_MASTER: "HCP Master",
    PATIENT_MASTER: "Patient Master",
    OWNER_MESSAGES: 'Owner Messages',
    COMMON_CONFIGURATION: "SMS Configuration",
    MICROSITE_CONFIGURATION: 'Microsite Configuration',
    ORDER: 'Orders',
    B2B_ORDER: 'Orders',
    COBRADING_ORDER: 'Co-Branding Order',
    ADVANCE_PAYMENT_PENDING: "Orders",
    ADVANCE_PAYMENT_FAILED: 'Payment Failed',
    RECIEVED: 'Received',
    CONFIRMED: 'Confirmed',
    IN_TRANSIT: 'In Transit',
    DELIVERED: 'Delivered',
    CANCELLED: 'Cancelled',
    DELETED_ORDER:'Deleted Order',
    ORDER_LIST: 'Order List',
    SEARCH_CONFIGURATION: 'Search Configurations',
    CONFIGURE: "Configure HCP Microsite",
    BASE_CONFIGURATION: "Base Configuration",
    BASE_TEMPLATE: "Base Template",
    SHIPPING_METHODS: "Shipping Methods",
    SHIPPING_RATES: "Shipping Rates",
    SHIPPING_ZONES: "Shipping Zones",
    PAYMENT_GATEWAY_CONFIGURATION: "Payment Gateway",
    HOME_PAGE_CONFIG: "Home Page Configurations",
    PDF_CONFIG: "PDF Configurations",
    RESET_PASSWORD: "Reset Password",
    SUB_ADMIN: "Sub Admin",
    TRAIL_LENSES_ORDERS:"Trial Lenses Orders",
    TRAIL_ORDERS_LIST:"Trial Orders List",
    DELETE_CATELOGUE:'Delete Product',
    DELETE_RECOMMENDED_PRODUCT:'Delete Recommended Product'
}

export const countAPIResponse = {
    "advance_payment_pending_order": "advance_payment_pending_order",
    "advance_payment_failed_order": 'advance_payment_failed_order',
    'cancel_payment_order': 'cancel_payment_order',
    'confirm_order': 'confirm_order',
    'delivered_order': 'delivered_order',
    'received_order': 'received_order',
    'transit_order': 'transit_order',
}
export const UserEnum = {
    ADMIN_USERS: 1,
    B2B_USERS: 2,
    MICROSITE_ADMIN_USERS: 3,
    B2B2C_USERS: 4
}
export const UserUrlEnum = {
    [UserEnum.ADMIN_USERS]: 'admin-users',
    [UserEnum.B2B_USERS]: 'b2b-users',
    [UserEnum.MICROSITE_ADMIN_USERS]: 'microsite-admin-users',
    [UserEnum.B2B2C_USERS]: 'b2b2c-users'
}
export const UserTitleEnum = {
    [UserEnum.ADMIN_USERS]: 'Admin User',
    [UserEnum.B2B_USERS]: 'B2B User',
    [UserEnum.MICROSITE_ADMIN_USERS]: 'Microsite Admin User',
    [UserEnum.B2B2C_USERS]: 'B2B2C User'
}

export const RateUrlEnum = {
    Metal: 'metal-rate',
    Diamond: 'diamond-rate',
    'Color Stone': 'color-stone-rate',
    'Labour Charge': 'labour-charge-rate'
}

export const emailEnum = {
    verify: 1,
    unverify: 0
}
export const approveEnum = {
    approve: 1,
    unapprove: 0
}
export const GENDER_OPTION = [
    { name: 'Male', value: 1 },
    { name: 'Female', value: 2 }
]

export const PLAN_TYPE_OPTION = [
    'Website Design',
    'Digital Marketing',
    'Product Photography'
]

export const PLAN_DURATION = [
    { name: 'Yearly', value: 'yearly' },
    { name: 'Monthly', value: 'monthly' }
]

export const CAREER_TYPE = [
    'Full Time',
    'Part Time'
]

export const Permission = {


    GENERAL_MASTER: "GENERAL_MASTER",
    SOLITAIR_MASTER: "SOLITAIR_MASTER",

    SUPER_ADMIN: 'SUPER_ADMIN',
    SHOW_ALL: 'SHOW_ALL',

    GENERAL_CONFIGURATION: "SHOW_GENERAL_CONFIGURATION",
    PRODUCT_CONFIGURATION: "SHOW_PRODUCT_CONFIGURATIONS",
    FOOTER_DATA_STORE: "FOOTER_DATA_STORE",
    DEFAULT_FOOTER_LIST: "DEFAULT_FOOTER_LIST",

    CMS_LIST: "CMS_LIST",
    CMS_UPDATE: "CMS_UPDATE",
    CMS_STATUS: "CMS_STATUS",

    RETURN_REASON_LIST: "RETURN_REASON_LIST",
    RETURN_REASON_CREATE: "RETURN_REASON_CREATE",
    RETURN_REASON_UPDATE: "RETURN_REASON_UPDATE",
    RETURN_REASON_DELETE: "RETURN_REASON_DELETE",
    RETURN_REASON_STATUS: "RETURN_REASON_STATUS",

    GENDER_LIST: "GENDER_LIST",
    GENDER_CREATE: "GENDER_CREATE",
    GENDER_UPDATE: "GENDER_UPDATE",
    GENDER_DELETE: "GENDER_DELETE",
    GENDER_STATUS: "GENDER_STATUS",
    GENDER_MOVE: "GENDER_MOVE",

    FAQ_CREATE: "FAQ_CREATE",
    FAQ_UPDATE: "FAQ_UPDATE",
    FAQ_DELETE: "FAQ_DELETE",
    FAQ_LIST: "FAQ_LIST",
    FAQ_STATUS: "FAQ_STATUS",
    FAQ_MOVE: "FAQ_MOVE",

    GROUP_MASTER_LIST: "GROUP_MASTER_LIST",
    GROUP_MASTER_CREATE: "GROUP_MASTER_CREATE",
    GROUP_MASTER_UPDATE: "GROUP_MASTER_UPDATE",
    GROUP_MASTER_DELETE: "GROUP_MASTER_DELETE",
    GROUP_MASTER_STATUS: "GROUP_MASTER_STATUS",

    BANNER_LIST: "BANNER_LIST",
    BANNER_CREATE: "BANNER_CREATE",
    BANNER_UPDATE: "BANNER_UPDATE",
    BANNER_DELETE: "BANNER_DELETE",
    BANNER_STATUS: "BANNER_STATUS",

    SUBSCRIBE_REQ_LIST: "SUBSCRIBE_REQ_LIST",
    SUBSCRIBE_REQ_REPLY_EMAIL: "SUBSCRIBE_REQ_REPLY_EMAIL",
    SUBSCRIBE_REQ_STATUS: "SUBSCRIBE_REQ_STATUS",

    CONTACTUS_LIST: "CONTACTUS_LIST",
    CONTACTUS_DELETE: "CONTACTUS_DELETE",
    CONTACTUS_MAIL: "CONTACTUS_MAIL",
    CONTACTUS_DELETE_ALL: "CONTACTUS_DELETE_ALL",

    HCP_INQUIRY_STORE: "HCP_INQUIRY_STORE",
    HCP_INQUIRY_LIST: "HCP_INQUIRY_LIST",
    HCP_INQUIRY_MAIL_SEND: "HCP_INQUIRY_MAIL_SEND",
    HCP_INQUIRY_DELETE: "HCP_INQUIRY_DELETE",

    SOCIAL_SETTING: "SOCIAL_SETTING",
    SOCIAL_SETTING_SHOW: "SOCIAL_SETTING_SHOW",
    CONTACTUS_SETTING: "CONTACTUS_SETTING",
    CONTACTUS_SETTING_SHOW: "CONTACTUS_SETTING_SHOW",

    PRODUCT_TAG_LIST: "PRODUCT_TAG_LIST",
    PRODUCT_TAG_CREATE: "PRODUCT_TAG_CREATE",
    PRODUCT_TAG_UPDATE: "PRODUCT_TAG_UPDATE",
    PRODUCT_TAG_DELETE: "PRODUCT_TAG_DELETE",
    PRODUCT_TAG_STATUS: "PRODUCT_TAG_STATUS",

    CATALOGUE_LIST: "CATALOGUE_LIST",
    CATALOGUE_CREATE: "CATALOGUE_CREATE",
    CATALOGUE_UPDATE: "PRODUCT_UPDATE",
    CATALOGUE_DELETE: "PRODUCT_DELETE",
    CATALOGUE_STATUS: "CATALOGUE_STATUS",

    PRODUCT_REVIEW_LIST: "PRODUCT_REVIEW_LIST",
    PRODUCT_REVIEW_STATUS: "PRODUCT_REVIEW_STATUS",

    PRODUCT_IMPORT_HISTORY_LIST: "PRODUCT_IMPORT_HISTORY_LIST",
    PRODUCT_IMPORT_HISTORY_SHOW: "PRODUCT_IMPORT_HISTORY_SHOW",

    PRODUCT_SYNC_HISTORY_LIST: "PRODUCT_SYNC_HISTORY_LIST",

    COUNTRY_LIST: "COUNTRY_LIST",
    COUNTRY_CREATE: "COUNTRY_CREATE",
    COUNTRY_UPDATE: "COUNTRY_UPDATE",
    COUNTRY_DELETE: "COUNTRY_DELETE",
    COUNTRY_STATUS: "COUNTRY_STATUS",
    COUNTRY_EXPORT: "COUNTRY_EXPORT",

    STATE_LIST: "STATE_LIST",
    STATE_CREATE: "STATE_CREATE",
    STATE_UPDATE: "STATE_UPDATE",
    STATE_DELETE: "STATE_DELETE",
    STATE_STATUS: "STATE_STATUS",
    STATE_EXPORT: "STATE_EXPORT",
    STATE_IMPORT: "STATE_IMPORT",

    CITY_LIST: "CITY_LIST",
    CITY_CREATE: "CITY_CREATE",
    CITY_UPDATE: "CITY_UPDATE",
    CITY_DELETE: "CITY_DELETE",
    CITY_STATUS: "CITY_STATUS",
    CITY_EXPORT: "CITY_EXPORT",
    CITY_IMPORT: "CITY_IMPORT",

    CONTACT_ADDRESS_LIST: "CONTACT_ADDRESS_LIST",
    CONTACT_ADDRESS_CREATE: "CONTACT_ADDRESS_CREATE",
    CONTACT_ADDRESS_UPDATE: "CONTACT_ADDRESS_UPDATE",
    CONTACT_ADDRESS_DELETE: "CONTACT_ADDRESS_DELETE",
    CONTACT_ADDRESS_STATUS: "CONTACT_ADDRESS_STATUS",

    TITLE_CONFIGURATIONS: "TITLE_CONFIGURATIONS",

    QUICK_LINK_LIST: "QUICK_LINK_LIST",
    QUICK_LINK_CREATE: "QUICK_LINK_CREATE",
    QUICK_LINK_UPDATE: "QUICK_LINK_UPDATE",
    QUICK_LINK_SORT: "QUICK_LINK_SORT",
    QUICK_LINK_SHOW: "QUICK_LINK_SHOW",
    QUICK_LINK_DELETE: "QUICK_LINK_DELETE",

    EMAIL_TEMP_LIST: "EMAIL_TEMP_LIST",
    EMAIL_TEMP_UPDATE: "EMAIL_TEMP_UPDATE",
    EMAIL_TEMP_STATUS: "EMAIL_TEMP_STATUS",

    ADMIN_USER_LIST: "ADMIN_USER_LIST",
    ADMIN_USER_CREATE: "ADMIN_USER_CREATE",
    ADMIN_USER_SHOW: "ADMIN_USER_SHOW",
    ADMIN_USER_UPDATE: "ADMIN_USER_UPDATE",
    ADMIN_USER_DELETE: "ADMIN_USER_DELETE",
    ADMIN_USER_STATUS: "ADMIN_USER_STATUS",
    ADMIN_USER_DATA_EXPORT: "ADMIN_USER_DATA_EXPORT",

    CREATE_OWN_DESIGN_STORE: "CREATE_OWN_DESIGN_STORE",

    B2B_USER_LIST: "B2B_USER_LIST",
    B2B_USER_CREATE: "B2B_USER_CREATE",
    B2B_USER_SHOW: "B2B_USER_SHOW",
    B2B_USER_UPDATE: "B2B_USER_UPDATE",
    B2B_USER_DELETE: "B2B_USER_DELETE",
    B2B_USER_STATUS: "B2B_USER_STATUS",
    B2B_USER_APPROVE: "B2B_USER_APPROVE",
    B2B_USER_VERIFY_EMAIL: "B2B_USER_VERIFY_EMAIL",
    B2B_USER_DATA_EXPORT: "B2B_USER_DATA_EXPORT",

    PAYMENT_PENDING_LIST: "PAYMENT_PENDING_LIST",
    PAYMENT_FAILED_LIST: "PAYMENT_FAILED_LIST",
    PAYMENT_RECEIVED_LIST: "PAYMENT_RECEIVED_LIST",
    PAYMENT_CONFIRMED_LIST: "PAYMENT_CONFIRMED_LIST",
    INTRANSIT_LIST: "INTRANSIT_LIST",
    DELIVERED_LIST: "DELIVERED_LIST",
    CANCEL_ORDER_LIST: "CANCEL_ORDER_LIST",
    DELETED_ORDER_LIST: "DELETED_ORDER_LIST",

    MICROSITE_ADMIN_USER_LIST: "MICROSITE_ADMIN_USER_LIST",
    MICROSITE_ADMIN_USER_CREATE: "MICROSITE_ADMIN_USER_CREATE",
    MICROSITE_ADMIN_USER_SHOW: "MICROSITE_ADMIN_USER_SHOW",
    MICROSITE_ADMIN_USER_UPDATE: "MICROSITE_ADMIN_USER_UPDATE",
    MICROSITE_ADMIN_USER_DELETE: "MICROSITE_ADMIN_USER_DELETE",
    MICROSITE_ADMIN_USER_STATUS: "MICROSITE_ADMIN_USER_STATUS",
    MICROSITE_ADMIN_USER_DATA_EXPORT: "MICROSITE_ADMIN_USER_DATA_EXPORT",

    B2B2C_USER_LIST: "B2B2C_USER_LIST",
    B2B2C_USER_SHOW: "B2B2C_USER_SHOW",
    B2B2C_USER_DELETE: "B2B2C_USER_DELETE",
    B2B2C_USER_STATUS: "B2B2C_USER_STATUS",
    B2B2C_USER_APPROVE: "B2B2C_USER_APPROVE",
    B2B2C_USER_VERIFY_EMAIL: "B2B2C_USER_VERIFY_EMAIL",
    B2B2C_USER_DATA_EXPORT: "B2B2C_USER_DATA_EXPORT",

    CART_LIST: "CART_LIST",
    CART_SHOW_PRODUCT: "CART_SHOW_PRODUCT",
    CART_EXPORT: "CART_EXPORT",

    LOGIN_REPORT: "LOGIN_REPORT",

    CATEGORY_LIST: "CATEGORY_LIST",
    CATEGORY_CREATE: "CATEGORY_CREATE",
    CATEGORY_UPDATE: "CATEGORY_UPDATE",
    CATEGORY_DELETE: "CATEGORY_DELETE",
    CATEGORY_STATUS: "CATEGORY_STATUS",

    SUB_CATEGORY_LIST: "SUB_CATEGORY_LIST",
    SUB_CATEGORY_CREATE: "SUB_CATEGORY_CREATE",
    SUB_CATEGORY_UPDATE: "SUB_CATEGORY_UPDATE",
    SUB_CATEGORY_DELETE: "SUB_CATEGORY_DELETE",
    SUB_CATEGORY_STATUS: "SUB_CATEGORY_STATUS",

    DYNAMIC_CATEGORY_LIST: "DYNAMIC_CATEGORY_LIST",

    CATEGORY_TYPE_LIST: "CATEGORY_TYPE_LIST",
    CATEGORY_TYPE_CREATE: "CATEGORY_TYPE_CREATE",
    CATEGORY_TYPE_UPDATE: "CATEGORY_TYPE_UPDATE",
    CATEGORY_TYPE_DELETE: "CATEGORY_TYPE_DELETE",
    CATEGORY_TYPE_STATUS: "CATEGORY_TYPE_STATUS",

    SORT_CATEGORY_LIST: "SORT_CATEGORY_LIST",

    PRODUCT_LIST: "PRODUCT_LIST",
    PRODUCT_CREATE: "PRODUCT_CREATE",
    PRODUCT_UPDATE: "PRODUCT_UPDATE",
    PRODUCT_DELETE: "PRODUCT_DELETE",
    PRODUCT_STATUS: "PRODUCT_STATUS",
    PRODUCT_REMOVE_IMAGES: "PRODUCT_REMOVE_IMAGES",
    PRODUCT_EXPORT: "PRODUCT_EXPORT",
    PRODUCT_SYNC: "PRODUCT_SYNC",

    MASTER_PRODUCT_LIST: "Product Master",

    SLUG_MASTER_LIST: "SLUG_MASTER_LIST",
    SLUG_MASTER_CREATE: "SLUG_MASTER_CREATE",
    SLUG_MASTER_UPDATE: "SLUG_MASTER_UPDATE",
    SLUG_MASTER_DELETE: "SLUG_MASTER_DELETE",
    SLUG_MASTER_STATUS: "SLUG_MASTER_STATUS",

    TAX_RATE_LIST: "TAX_RATE_LIST",

    HCP_LIST: "ACCOUNT_LIST",
    HCP_CREATE: "ACCOUNT_CREATE",
    HCP_UPDATE: "ACCOUNT_UPDATE",
    HCP_DELETE: "ACCOUNT_DELETE",
    HCP_STATUS: "ACCOUNT_STATUS",
    HCP_SYNC: "ACCOUNT_SYNC",
    HCP_CALCULATE_SYNC: "ACCOUNT_CALCULATE_SYNC",
    HCP_SYNC_IMAGE: "PRODUCT_SYNC_IMAGE",

    PATIENT_LIST: "B2B2C_USER_LIST",
    PATIENT_VIEW: "B2B2C_USER_SHOW",

    ORDER_LIST: "PAYMENT_RECEIVED_LIST",

    TRANSACTION_LIST: "PAYMENT_CONFIRMED_LIST",

    NUMBER_GENERATOR_LIST: "NUMBER_GENERATOR_LIST",
    NUMBER_GENERATOR_CREATE: "NUMBER_GENERATOR_CREATE",
    NUMBER_GENERATOR_UPDATE: "NUMBER_GENERATOR_UPDATE",
    NUMBER_GENERATOR_DELETE: "NUMBER_GENERATOR_DELETE",
    NUMBER_GENERATOR_STATUS: "NUMBER_GENERATOR_STATUS",

    RATE_CARD_METAL_LIST: "RATE_CARD_METAL_LIST",
    RATE_CARD_METAL_CREATE: "RATE_CARD_METAL_CREATE",
    RATE_CARD_METAL_UPDATE: "RATE_CARD_METAL_UPDATE",
    RATE_CARD_METAL_PRICE: "RATE_CARD_METAL_PRICE",
    RATE_CARD_METAL_STATUS: "RATE_CARD_METAL_STATUS",
    RATE_CARD_METAL_HISTORY: "RATE_CARD_METAL_HISTORY",

    RATE_PLAN_LIST: "RATE_PLAN_LIST",
    RATE_PLAN_CREATE: "RATE_PLAN_CREATE",
    RATE_PLAN_UPDATE: "RATE_PLAN_UPDATE",
    RATE_PLAN_PRICE_DETAIL: "RATE_PLAN_PRICE_DETAIL",
    RATE_PLAN_STATUS: "RATE_PLAN_STATUS",

    RATE_CARD_DIAMOND_LIST: "RATE_CARD_DIAMOND_LIST",
    RATE_CARD_DIAMOND_CREATE: "RATE_CARD_DIAMOND_CREATE",
    RATE_CARD_DIAMOND_UPDATE: "RATE_CARD_DIAMOND_UPDATE",
    RATE_CARD_DIAMOND_PRICE: "RATE_CARD_DIAMOND_PRICE",
    RATE_CARD_DIAMOND_STATUS: "RATE_CARD_DIAMOND_STATUS",
    RATE_CARD_DIAMOND_HISTORY: "RATE_CARD_DIAMOND_HISTORY",

    RATE_CARD_COLOR_STONE_LIST: "RATE_CARD_COLOR_STONE_LIST",
    RATE_CARD_COLOR_STONE_CREATE: "RATE_CARD_COLOR_STONE_CREATE",
    RATE_CARD_COLOR_STONE_UPDATE: "RATE_CARD_COLOR_STONE_UPDATE",
    RATE_CARD_COLOR_STONE_PRICE: "RATE_CARD_COLOR_STONE_PRICE",
    RATE_CARD_COLOR_STONE_STATUS: "RATE_CARD_COLOR_STONE_STATUS",
    RATE_CARD_COLOR_STONE_HISTORY: "RATE_CARD_COLOR_STONE_HISTORY",

    RATE_CARD_LABOUR_CHARGE_LIST: "RATE_CARD_LABOUR_CHARGE_LIST",
    RATE_CARD_LABOUR_CHARGE_CREATE: "RATE_CARD_LABOUR_CHARGE_CREATE",
    RATE_CARD_LABOUR_CHARGE_UPDATE: "RATE_CARD_LABOUR_CHARGE_UPDATE",
    RATE_CARD_LABOUR_CHARGE_PRICE: "RATE_CARD_LABOUR_CHARGE_PRICE",
    RATE_CARD_LABOUR_CHARGE_STATUS: "RATE_CARD_LABOUR_CHARGE_STATUS",
    RATE_CARD_LABOUR_CHARGE_HISTORY: "RATE_CARD_LABOUR_CHARGE_HISTORY",

    OWNER_MESSAGE_LIST: "OWNER_MESSAGE_LIST",
    OWNER_MESSAGE_CREATE: "OWNER_MESSAGE_CREATE",
    OWNER_MESSAGE_UPDATE: "OWNER_MESSAGE_UPDATE",
    OWNER_MESSAGE_DELETE: "OWNER_MESSAGE_DELETE",
    OWNER_MESSAGE_STATUS: "OWNER_MESSAGE_STATUS",

    ABOUTUS_CREATE: "ABOUTUS_CREATE",

    MASTER_MODULE: 'MASTER_MODULE',
    MASTER_IS_MASTER: 'MASTER_IS_MASTER',
    MASTTER_CATEGORY_CUSTOMIZE: 'MASTTER_CATEGORY_CUSTOMIZE',
    MASTTER_COLLECTION_CUSTOMIZE: 'MASTTER_COLLECTION_CUSTOMIZE',
    MASTTER_CATALOGUE_CUSTOMIZE: 'MASTTER_CATALOGUE_CUSTOMIZE',
    MASTTER_CODE: 'MASTTER_CODE',
    MASTER_MODULE_STATUS: 'MASTER_MODULE_STATUS',
    COLLECTION_CREATE: "COLLECTION_CREATE",
    COLLECTION_UPDATE: "COLLECTION_UPDATE",
    COLLECTION_DELETE: "COLLECTION_DELETE",
    COLLECTION_STATUS: "COLLECTION_STATUS",
    COLLECTION_FILTER_CREATED: "COLLECTION_FILTER_CREATED",
    COLLECTION_FILTER_LIST: "COLLECTION_FILTER_LIST",
    COLLECTION_FILTER_UPDATE: "COLLECTION_FILTER_UPDATE",
    COLLECTION_FILTER_DELETE: "COLLECTION_FILTER_DELETE",
    COLLECTION_FILTER_SHOW: "COLLECTION_FILTER_SHOW",

    SETTING_CREATE: "SETTING_CREATE",
    SETTING_SHOW: "SETTING_SHOW",

    USER_EXPORT: 'USER_EXPORT',
    USER_IMPORT: 'USER_IMPORT',
    ACCOUNT_EXPORT: 'ACCOUNT_EXPORT',
    ACCOUNT_IMPORT: 'ACCOUNT_IMPORT',

    PRODUCT_IMPORT: 'PRODUCT_IMPORT',

    CLIENT_ORDER_LIST: "CLIENT_ORDER_LIST",
    WEBSITE_CONFIGURATION_CREATE: "WEBSITE_CONFIGURATION_CREATE",
    ORDER_HISTORY_EXCEL: "ORDER_HISTORY_EXCEL",
    MOST_VIEW_CATEGORY_TYPE_EXPORT: "MOST_VIEW_CATEGORY_TYPE_EXPORT",
    MOST_VIEW_CATEGORY_EXPORT: "MOST_VIEW_CATEGORY_EXPORT",
    MOST_VIEW_PRODUCT_EXPORT: "MOST_VIEW_PRODUCT_EXPORT",
    MOST_VIEW_COLLECTION_EXPORT: "MOST_VIEW_COLLECTION_EXPORT",
    ORDER_TRANSACTION_EXCEL: "ORDER_TRANSACTION_EXCEL",
    POPULAR_SEARCH_ADD: "POPULAR_SEARCH_ADD",

    CONFIGURE: 'CONFIGURE',

    HOME_PAGE_CONFIG_LIST: "HOME_PAGE_CONFIG_LIST",
    HOME_PAGE_CONFIG_CREATE: "HOME_PAGE_CONFIG_CREATE",
    HOME_PAGE_CONFIG_UPDATE: "HOME_PAGE_CONFIG_UPDATE",
    HOME_PAGE_CONFIG_DELETE: "HOME_PAGE_CONFIG_DELETE",

    SHIPPING_RATE_LIST: "SHIPPING_RATE_LIST",
    SHIPPING_RATE_CREATE: "SHIPPING_RATE_CREATE",
    SHIPPING_RATE_UPDATE: "SHIPPING_RATE_UPDATE",
    
    TRAIL_LENSES_ORDER_LIST:'TRIAL_LENSES_ORDER_LIST'
}

const GENERALMASTER = [
    "PRICE_RANGE_LIST",
    "COLOR_STONE_LIST",
    "LABOUR_CHARGE_LIST",
    "LENGTH_LIST",
    "RETURN_REASON_LIST",
    "SHOP_LIST",
    "GAUGE_LIST",
    "OCCASION_LIST",
    "GENDER_LIST",
    "FAQ_LIST",
    "EVENT_LIST",
    "COUPON_LIST",
    "GROUP_MASTER_LIST",
    "TESTIMONIAL_LIST",
    "BLOG_LIST",
    "SIZE_LIST",
    "BANNER_LIST",
];

export const removeWebsite = [
    "Price",
    "Color Stone",
    "Metal Price Type",
    "Labour Charge",
    "Labour Charge Type",
    "Length",
    "Return Reasons",
    "Shop For Module",
    "Gauge",
    "Occasion",
    "Gender",
    "event",
    "Group Master",
    "Testimonial",
    "blog",
    "ringsize",

    "Diamond Quality",
    "Diamond Sieves",
    "Diamond Shapes",
    "Diamond Clarities",
    "Diamond Color",

    "Solitaire Eye Cleans",
    "Solitaire Labs",
    "Solitaire Symmetry",
    "Solitaire Polish",
    "Solitaire Shape",
    "Solitaire Clarity",
    "Solitaire Cut",
    "Solitaire Color",

    "Career Designation",
    "Career Location",
    "Career Reference",

    "Metal Purity",
    "Metal Type",
    "Metal Weight",

    "Product Wear Tag",
    "Product Looks Tag",
    "Product group",

    "Bangle Bracelets",
    "Bangle Size",
]

export const orderStatus = {
    Pending: 'Pending',
    Accepted: 'Accepted',
    Confirmed: 'Confirmed',
    Out_for_Delivery: 'Out for Delivery',
    Delivered: 'Delivered',
    Rejected: 'Rejected',
    Cancelled: 'Cancelled',
    Returned: 'Returned',
    Refunded: 'Refunded',
    Cancelled_Refunded: 'Cancelled & Refunded',
    Returned_Refunded: 'Returned & Refunded'
}


export const orderStatusArray = [
    { name: 'Pending', code: '1' },
    { name: 'Accepted', code: '2' },
    { name: 'Confirmed', code: '3' },
    { name: 'Out for Delivery', code: '4' },
    { name: 'Delivered', code: '5' },
    { name: 'Rejected', code: '6' },
    { name: 'Cancelled', code: '7' },
    { name: 'Returned', code: '8' },
    { name: 'Refunded', code: '9' },
    { name: 'Cancelled Refunded', code: '10' },
    { name: 'Returned Refunded', code: '11' },
]

export const paymentStatus = {
    'cod': 'COD',
    'razorpay': 'Razorpay',
    'stripe' : 'Stripe'
}


export const paymentMethodArray = [
    { name: "COD", code: "1" },
    { name: "Razorpay", code: "2" },
    { name: "Stripe", code: "3" },
    { name: "CC Avenue", code: '4' },
]

export const ADD_EDIT_BASE_CONFIGURATION = "Add/Edit Base Configuration";