trigger:
  branches:
    include:
    - '*'

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonarqube_Brainvire_Inhouse_server'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'NodeJS-Base-Structure-sonarqube'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'