export const permissionsArray = {
	USER_MANAGEMENT: {
		ListAccess: 'LIST_USERS',
		ViewAccess: 'VIEW_USER_DETAILS',
		EditAccess: 'EDIT_USER_DETAILS',
		ChangeStatusAccess: 'DEACTIVATE_USER',
		DeleteAccess: 'DELETE_USER_DETAILS',
	},
	LEVEL_MANAGEMENT: {
		ListAccess: 'LIST_LEVELS',
		ViewAccess: 'GET_LEVELS',
		AddAccess: 'ADD_LEVELS',
		EditAccess: 'EDIT_LEVELS',
		ChangeStatusAccess: 'DEACTIVATE_LEVELS',
		DeleteAccess: 'DELETE_LEVELS',
	},
	TOPIC_MANAGEMENT: {
		ListAccess: 'LIST_TOPICS',
		ViewAccess: 'GET_TOPICS',
		AddAccess: 'ADD_TOPICS',
		EditAccess: 'EDIT_TOPICS',
		ChangeStatusAccess: 'DEACTIVATE_TOPICS',
		DeleteAccess: 'DELETE_TOPICS',
	},
	LESSON_MANAGEMENT: {
		ListAccess: 'LIST_LESSONS',
		ViewAccess: 'GET_LESSONS',
		AddAccess: 'ADD_LESSONS',
		EditAccess: 'EDIT_LESSONS',
		ChangeStatusAccess: 'DEACTIVATE_LESSONS',
		DeleteAccess: 'DELETE_LESSONS',
	},
	ACTIVITY_MANAGEMENT: {
		ListAccess: 'LIST_ACTIVITY',
		ViewAccess: 'GET_ACTIVITY',
		AddAccess: 'ADD_ACTIVITY',
		EditAccess: 'EDIT_ACTIVITY',
		ChangeStatusAccess: 'DEACTIVATE_ACTIVITY',
		DeleteAccess: 'DELETE_ACTIVITY',
	},
	SEASONAL_TOPIC_MANAGEMENT: {
		ListAccess: 'LIST_SEASONAL_TOPICS',
		ViewAccess: 'GET_SEASONAL_TOPICS',
		AddAccess: 'ADD_SEASONAL_TOPICS',
		EditAccess: 'EDIT_SEASONAL_TOPICS',
		ChangeStatusAccess: 'DEACTIVATE_SEASONAL_TOPICS',
		DeleteAccess: 'DELETE_SEASONAL_TOPICS',
	},
	SEASONAL_LESSON_MANAGEMENT: {
		ListAccess: 'LIST_SEASONAL_LESSONS',
		ViewAccess: 'GET_SEASONAL_LESSONS',
		AddAccess: 'ADD_SEASONAL_LESSONS',
		EditAccess: 'EDIT_SEASONAL_LESSONS',
		ChangeStatusAccess: 'DEACTIVATE_SEASONAL_LESSONS',
		DeleteAccess: 'DELETE_SEASONAL_LESSONS',
	},
	SEASONAL_ACTIVITY_MANAGEMENT: {
		ListAccess: 'LIST_SEASONAL_ACTIVITY',
		ViewAccess: 'GET_SEASONAL_ACTIVITY',
		AddAccess: 'ADD_SEASONAL_ACTIVITY',
		EditAccess: 'EDIT_SEASONAL_ACTIVITY',
		ChangeStatusAccess: 'DEACTIVATE_SEASONAL_ACTIVITY',
		DeleteAccess: 'DELETE_SEASONAL_ACTIVITY',
	},
	SOP_LEVEL_MANAGEMENT: {
		ListAccess: 'LIST_SOP_LEVELS',
		ViewAccess: 'GET_SOP_LEVELS',
		AddAccess: 'ADD_SOP_LEVELS',
		EditAccess: 'EDIT_SOP_LEVELS',
		ChangeStatusAccess: 'DEACTIVATE_SOP_LEVELS',
		DeleteAccess: 'DELETE_SOP_LEVELS',
	},
	SOP_ACTIVITY_MANAGEMENT: {
		ListAccess: 'LIST_SOP_ACTIVITY',
		ViewAccess: 'GET_SOP_ACTIVITY',
		AddAccess: 'ADD_SOP_ACTIVITY',
		EditAccess: 'EDIT_SOP_ACTIVITY',
		ChangeStatusAccess: 'DEACTIVATE_SOP_ACTIVITY',
		DeleteAccess: 'DELETE_SOP_ACTIVITY',
	},
	SOP_EXAM_RESULT: {
		ViewAccess: 'SOP_EXAM_RESULTS',
	},
	CMS_MANAGEMENT: {
		ListAccess: 'LIST_CMS',
		ViewAccess: 'GET_CMS',
		AddAccess: 'ADD_CMS',
		EditAccess: 'EDIT_CMS',
		ChangeStatusAccess: 'DEACTIVATE_CMS',
		DeleteAccess: 'DELETE_CMS',
	},
	KARAOKE_MANAGEMENT: {
		ListAccess: 'LIST_KARAOKE',
		ViewAccess: 'GET_KARAOKE',
		AddAccess: 'ADD_KARAOKE',
		EditAccess: 'EDIT_KARAOKE',
		ChangeStatusAccess: 'DEACTIVATE_KARAOKE',
		DeleteAccess: 'DELETE_KARAOKE',
	},
	SUBSCRIPTION_MANAGEMENT: {
		ListAccess: 'LIST_SUBSCRIPTION',
		ViewAccess: 'GET_SUBSCRIPTION',
		AddAccess: 'ADD_SUBSCRIPTION',
		EditAccess: 'EDIT_SUBSCRIPTION',
		ChangeStatusAccess: 'DEACTIVATE_SUBSCRIPTION',
		DeleteAccess: 'DELETE_SUBSCRIPTION',
	},
	CATEGORY_MANAGEMENT: {
		ListAccess: 'LIST_CATEGORY',
		ViewAccess: 'GET_CATEGORY',
		AddAccess: 'ADD_CATEGORY',
		EditAccess: 'EDIT_CATEGORY',
		ChangeStatusAccess: 'DEACTIVATE_CATEGORY',
		DeleteAccess: 'DELETE_CATEGORY',
	},
	CATEGORY_FLASHCARD_MANAGEMENT: {
		AddAccess: 'ADD_FLASHCARD',
		ViewAccess: 'GET_FLASHCARD',
		ListAccess: 'LIST_FLASHCARD',
		EditAccess: 'EDIT_FLASHCARD',
		DeleteAccess: 'DELETE_FLASHCARD',
		ChangeStatusAccess: 'DEACTIVATE_FLASHCARD',
	},
	COUNTRY_MANAGEMENT: {
		AddAccess: 'ADD_COUNTRY',
		ViewAccess: 'GET_COUNTRY',
		ListAccess: 'LIST_COUNTRY',
		EditAccess: 'EDIT_COUNTRY',
		DeleteAccess: 'DELETE_COUNTRY',
		ChangeStatusAccess: 'DEACTIVATE_COUNTRY',
	},
	PET_STORE_PRODUCT_MANAGEMENT: {
		AddAccess: 'ADD_PRODUCT',
		ViewAccess: 'GET_PRODUCT',
		ListAccess: 'LIST_PRODUCT',
		EditAccess: 'EDIT_PRODUCT',
		DeleteAccess: 'DELETE_PRODUCT',
		ChangeStatusAccess: 'DEACTIVATE_PRODUCT',
	},
	ONBOARDING_MANAGEMENT: {
		AddAccess: 'ADD_ONBOARDING',
		ViewAccess: 'GET_ONBOARDING',
		ListAccess: 'LIST_ONBOARDING',
		EditAccess: 'EDIT_ONBOARDING',
		DeleteAccess: 'DELETE_ONBOARDING',
		ChangeStatusAccess: 'DEACTIVATE_ONBOARDING',
	},
	PET_STORE_PRODUCT_VALUE_MANAGEMENT: {
		AddAccess: 'ADD_PRODUCT_VALUE',
		EditAccess: 'EDIT_PRODUCT_VALUE',
		DeleteAccess: 'DELETE_PRODUCT_VALUE',
	},
	PET_ATTRIBUTES_MANAGEMENT: {
		AddAccess: 'ADDING_MOOD_HEALTH_LEVELS',
		EditAccess: 'EDITING_MOODS_AND_HEALTH_LEVELS',
	},
	PET_CONDITIONS_MANAGEMENT: {
		ViewAccess: 'PET_CONDITIONS_MANAGEMENT',
	},
	PET_ROOMS_DISPLAY: {
		ViewAccess: 'PET_ROOMS_DISPLAY',
	},
	SETTINGS: {
		UpdateAccess: 'UPDATE_SETTINGS',
	},
	SOUND_MANAGEMENT: {
		AddAccess: 'ADD_SOUND_EVENT',
		ViewAccess: 'GET_SOUND_EVENT',
		ListAccess: 'LIST_SOUND_EVENT',
		EditAccess: 'EDIT_SOUND_EVENT',
		DeleteAccess: 'DELETE_SOUND_EVENT',
		ChangeStatusAccess: 'DEACTIVATE_SOUND_EVENT',
	},
	WHY_IT_WORKS: {
		AddAccess: 'ADD_WHY_IT_WORKS',
		ViewAccess: 'GET_WHY_IT_WORKS',
		ListAccess: 'LIST_WHY_IT_WORKS',
		EditAccess: 'EDIT_WHY_IT_WORKS',
		DeleteAccess: 'DELETE_WHY_IT_WORKS',
	},
	VOCABULARY: {
		ListAccess: 'LIST_VOCABULARY',
		DeleteAccess: 'DELETE_VOCABULARY',
	},
	SCHOOL_MANAGEMENT: {
		AddAccess: 'ADD_SCHOOL',
		ViewAccess: 'GET_SCHOOL',
		ListAccess: 'LIST_SCHOOL',
		EditAccess: 'EDIT_SCHOOL',
		DeleteAccess: 'DELETE_SCHOOL',
		ChangeStatusAccess: 'DEACTIVATE_SCHOOL',
	},
	TEACHER_MANAGEMENT: {
		AddAccess: 'ADD_TEACHER',
		ViewAccess: 'GET_TEACHER',
		ListAccess: 'LIST_TEACHER',
		EditAccess: 'EDIT_TEACHER',
		DeleteAccess: 'DELETE_TEACHER',
		ChangeStatusAccess: 'DEACTIVATE_TEACHER',
	},
	CLASSROOM_MANAGEMENT: {
		AddAccess: 'ADD_CLASSROOM',
		ViewAccess: 'GET_CLASSROOM',
		ListAccess: 'LIST_CLASSROOM',
		EditAccess: 'EDIT_CLASSROOM',
		DeleteAccess: 'DELETE_CLASSROOM',
		ChangeStatusAccess: 'DEACTIVATE_CLASSROOM',
	},
	CHILD_MANAGEMENT: {
		AddAccess: 'ADD_CHILD',
		ViewAccess: 'GET_CHILD',
		ListAccess: 'LIST_CHILD',
		EditAccess: 'EDIT_CHILD',
		DeleteAccess: 'DELETE_CHILD',
		ChangeStatusAccess: 'DEACTIVATE_CHILD',
	},
	VIDEO_MANAGEMENT: {
		AddAccess: 'ADD_VIDEO_CONTENT',
		ViewAccess: 'GET_VIDEO_CONTENT',
		ListAccess: 'LIST_VIDEO_CONTENT',
		EditAccess: 'EDIT_VIDEO_CONTENT',
		DeleteAccess: 'DELETE_VIDEO_CONTENT',
		ChangeStatusAccess: 'DEACTIVATE_VIDEO_CONTENT',
	},
};
