export const PERMISSION_LIST = {
	Dashboard: {
		DashboardAccess: '',
	},
	SubAdmin: {
		ListAccess: 'LIST_SUB_ADMIN',
		AddAccess: 'CREATE_SUB_ADMIN',
		EditAccess: 'UPDATE_ADMIN_EDIT',
		ChangeStatusAccess: 'SUB_ADMIN_CHANGE_STATUS',
		DeleteAccess: 'DELETE_SUB_ADMIN',
		GroupDeleteAcsess: 'GROUP_DELETE_SUB_ADMIN',
		ChangePasswordAccess: 'CHANGE_PASSWORD_SUB_ADMIN',
	},
	UserManagement: {
		ListAccess: 'USERS_LIST_PAGINATION',
		AddAccess: '',
		EditAccess: 'USER_UPDATE',
		ViewAccess: 'USER_VIEW',
		ChangeStatusAccess: 'USER_UPDATE_STATUS',
		DeleteAccess: 'USER_DELETE',
		GroupDeleteAcsess: 'GROUP_DELETE_USERS',
		ChangePasswordAccess: 'CHANGE_USER_PASSWORD',
	},
	FAQ: {
		ListAccess: 'FAQ_LIST_TOPIC',
		AddAccess: 'FAQ_CREATE_TOPIC',
		EditAccess: 'FAQ_UPDATE_TOPIC',
		ChangeStatusAccess: 'FAQ_QA_CHANGE_STATUS',
		DeleteAccess: 'FAQ_DELETE_TOPIC',
		GroupDeleteAcsess: 'GROUP_DELETE_FAQ_TOPIC',
	},
	CMS: {
		ListAccess: 'FETCH_CMS',
		AddAccess: 'CREATE_CMS',
		EditAccess: 'UPDATE_CMS',
		ChangeStatusAccess: 'UPDATE_CMS_STATUS',
		DeleteAccess: 'DELETE_CMS',
		GroupDeleteAcsess: 'GROUP_DELETE_CMS',
	},
	Enquiry: {
		ListAccess: 'FETCH_ENQUIRY',
		AddAccess: 'CREATE_ENQUIRY',
		ChangeStatusAccess: 'UPDATE_STATUS',
		DeleteAccess: 'DELETE_ENQUIRY',
		GroupDeleteAcsess: 'GROUP_DELETE_ENQUIRY',
	},
	EmailTemplate: {
		ListAccess: 'EMAIL_TEMPLATE_LIST',
		AddAccess: 'EMAIL_TEMPLATE_CREATE',
		EditAccess: 'EMAIL_TEMPLATE_UPDATE',
		ChangeStatusAccess: 'EMAIL_STATUS_UPDATE',
		DeleteAccess: 'EMAIL_TEMPLATE_DELETE',
		GroupDeleteAcsess: 'GROUP_EMAIL_TEMPLATE_DELETE',
	},
	Announcement: {
		ListAccess: 'FETCH_ANNOUNCEMENT_WITH_FILTERS',
		AddAccess: 'CREATE_ANNOUNCEMENT',
		ViewAccess: 'FETCH_SINGLE_ANNOUNCEMENT',
	},
	Role: {
		ListAccess: 'ROLE_LIST',
		AddAccess: 'ROLE_CREATE',
		EditAccess: 'ROLE_UPDATE',
		ChangeStatusAccess: 'ROLE_CHANGE_STATUS',
		DeleteAccess: 'ROLE_DELETE',
	},
	Permission: {
		ListAccess: 'FETCH_MODULE_WISE_PERMISSIONS',
		createAccess: 'CREATE_PERMISSION',
	},
	Settings: {
		ListAccess: 'SETTING_LIST',
		EditAccess: 'UPDATE_AND_CREATE_SETTING',
	},
	BsMedia: {
		ListAccess: 'FETCH_LIST_OF_BS_MEDIA',
		AddFolderAccess: 'FOLDER_CREATE_BS_MEDIA',
		RenameAccess: 'RENAME_BS_MEDIA',
		DeleteAccess: 'GROUP_DELETE_BS_MEDIA',
		MoveAccess: 'MOVE_BS_MEDIA',
		ViewAccess: 'GET_BS_MEDIA_DETAIL',
	},
	Banner: {
		ListAccess: 'FETCH_BANNER',
		EditAccess: 'UPDATE_BANNER',
		AddAccess: 'CREATE_BANNER',
		ChangeStatusAccess: 'UPDATE_BANNER_STATUS',
		DeleteAccess: 'DELETE_SINGLE_BANNER',
		GroupDeleteAcsess: 'DELETE_GROUP_BANNER',
	},

	Country: {
		ListAccess: 'FETCH_COUNTRIES_WITH_PAGINATION',
		EditAccess: 'UPDATE_COUNTRY',
		AddAccess: 'CREATE_COUNTRY',
		ChangeStatusAccess: 'CHANGE_COUNTRY_STATUS',
		DeleteAccess: 'DELETE_COUNTRY',
		GroupDeleteAcsess: 'GROUP_DELETE_COUNTRY',
	},

	State: {
		ListAccess: 'FETCH_STATES',
		EditAccess: 'UPDATE_STATE',
		AddAccess: 'CREATE_STATE',
		ChangeStatusAccess: 'CHANGE_STATE_STATUS',
		DeleteAccess: 'DELETE_STATE',
		GroupDeleteAcsess: 'GROUP_DELETE_STATES',
	},
	Coupon: {
		ListAccess: 'FETCH_OFFERS',
		EditAccess: 'UPDATE_OFFER',
		AddAccess: 'CREATE_OFFER',
		ChangeStatusAccess: 'UPDATE_OFFER_STATUS',
		DeleteAccess: 'DELETE_OFFER',
		GroupDeleteAcsess: 'GROUP_DELETE_OFFER',
	},
	City: {
		ListAccess: 'FETCH_CITIES',
		EditAccess: 'UPDATE_CITY',
		AddAccess: 'CREATE_CITY',
		ChangeStatusAccess: 'CHANGE_CITY_STATUS',
		DeleteAccess: 'DELETE_CITY',
		GroupDeleteAcsess: 'GROUP_DELETE_CITIES',
	},
	UserReport: {
		ListAccess: 'USER_REPORTS',
		ChangeStatusAccess: 'USER_REPORT_CHANGE_STATUS',
		DeleteAccess: 'DELETE_USER_REPORT',
		GroupDeleteAcsess: 'GROUP_DELETE_USER_REPORT',
	},
	Suggestion: {
		ListAccess: 'SUGGESTION_LIST',
		ChangeStatusAccess: 'UPDATE_SUGGESTION_STATUS',
		EditAccess: 'UPDATE_SUGGESTION',
		AddAccess: 'CREATE_SUGGESTION',
		DeleteAccess: 'DELETE_SUGGESTION',
		GroupDeleteAcsess: 'GROUP_DELETE_SUGGESTION',
	},
	Review: {
		ListAccess: 'FETCH_REVIEWS',
		AddAccess: 'CREATE_REVIEW',
		ChangeStatusAccess: 'UPDATE_STATUS_REVIEW',
		DeleteAccess: 'DELETE_REVIEW',
		GroupDeleteAcsess: 'GROUP_DELETE_REVIEW',
	},
	ActivityTracking: {
		ListAccess: 'FETCH_ACTIVITIES',
		AddAccess: 'CREATE_ACTIVITY',
		DeleteAccess: 'DELETE_ACTIVITY',
		GroupDeleteAcsess: 'GROUP_DELETE_ACITIVITY',
	},
};
