export const WhatsAppActionTypes = {
    SET_WHATSAPP_NUMBER: "SET_WHATSAPP_NUMBER",
    SET_GENERAL_CONF_NUMBER: "SET_GENERAL_CONF_NUMBER",
    SET_GENERAL_CONF_COUNTRY: "SET_GENERAL_CONF_COUNTRY",
    SET_WHATSAPP_FEED: "SET_WHATSAPP_FEED",
    SET_EMAIL:"SET_EMAIL_VALUE",
    SET_MOBILE_NUMBER:"SET_MOBILE_NUMBER",
    SET_COUNTRY_CODE:"SET_COUNTRY_CODE",
    SET_SITE_LOGO:"SET_SITE_LOGO",
}