const statesAndProvinces = {
  CA: [
    { code: "NL", name: "Newfoundland and Labrador" },
    { code: "PE", name: "Prince Edward Island" },
    { code: "NS", name: "Nova Scotia" },
    { code: "NB", name: "New Brunswick" },
    { code: "QC", name: "Quebec" },
    { code: "ON", name: "Ontario" },
    { code: "MB", name: "Manitoba" },
    { code: "SK", name: "Saskatchewan" },
    { code: "AB", name: "Alberta" },
    { code: "BC", name: "British Columbia" },
    { code: "YT", name: "Yukon" },
    { code: "NT", name: "Northwest Territories" },
    { code: "NU", name: "Nunavut" },
  ],
  US: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolin" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolin" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
  ],
  IND: [
    { name: '', code: '' },
    { name: "Nicobar Islands", code: "AN"},
    { name: "Andhra Pradesh", code: "AP"},
    { name: "Arunachal Pradesh", code: "AR"},
    { name: "Assam", code:	"AS"},
    { name: "Bihar", code:	"BR"},
    { name: "Chandigarh", code:	"CH"},
    { name: "Chhattisgarh", code:	"CT"},
    { name: "Dadra and Nagar Haveli", code: "DN"},
    { name: "Daman and  Diu", code: "DD"},
    { name: "Delhi", code:	"DL"},
    { name: "Goa", code:	"GA"},
    { name: "Gujarat", code:	"GJ"},
    { name: "Haryana", code:	"HR"},
    { name: "Himachal Pradesh", code: "HP"},
    { name: "Jammu and Kashmir", code: "JK"},
    { name: "Jharkhand", code:	"JH"},
    { name: "Karnataka", code:	"KA"},
    { name: "Kerala", code:	"KL"},
    { name: "Lakshadweep", code:	"LD"},
    { name: "Madhya Pradesh", code: "MP"},
    { name: "Maharashtra", code:	"MH"},
    { name: "Manipur", code:	"MN"},
    { name: "Meghalaya", code:	"ML"},
    { name: "Mizoram", code:	"MZ"},
    { name: "Nagaland", code:	"NL"},
    { name: "Odisha", code:	"OR"},
    { name: "Puducherry", code:	"PY"},
    { name: "Punjab", code:	"PB"},
    { name: "Rajasthan", code:	"RJ"},
    { name: "Sikkim", code:	"SK"},
    { name: "Tamil", code: "Nadu"},
    { name: "Telangana", code:	"TG"},
    { name: "Tripura", code:	"TR"},
    { name: "Uttar Pradesh", code: "UP"},
    { name: "Uttarakhand", code:	"UT"},
    { name: "West Bengal", code: "WB"},
  ]
};

export default statesAndProvinces;
