version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/www.commentsold.com/application/commentsold-front
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: deployment_scripts/codedeploy_after_install.sh
      timeout: 300
      runas: ubuntu