import type { NextPage } from 'next';
import { useCallback } from 'react';
import Head from 'next/head';
import FacebookLogin from 'src/component/customFacebook/facebook';

const Home: NextPage = () => {
  const handleFacebookData = useCallback((data: any) => {
    console.log(data);
  }, []);

  return (
    <div>
      <Head>
        <title>Custom Facebook Login & Signup</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <FacebookLogin onClose={handleFacebookData} />
    </div>
  );
};

export default Home;
