// All modules error messages
export const Message = {
  SOMETHING_WENT_WRONG: "Something Went Wrong!",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_PATTERN: "Invalid email address. E.g. example@email.com",
  PASSWORD_PATTERN:
    "Password must contain 1 upper case, 1 lower case, 1 number, 1 special character ( @ ! $ % ^ & #) & minimum 8 characters to maximum 40 characters",
  MOBILE_PATTERN: "Invalid mobile number.",
  COMPANYNAME_REQUIRED: "Company Name is required",
  MOBILENUMBER_REQUIRED: "Mobile Number is required",
  NAME_REQUIRED: "Name is Required",
  FIRSTNAME_REQUIRED: "First Name is required",
  LASTNAME_REQUIRED: "Last Name is required",
  GENDER_REQUIRED: "Gender is Required",
  CITY_REQUIRED: "City is Required",
  WHITE_SPACE: " Whitespace not allowed at the beginning and at the end.",
  COUNTRY_REQUIRED: "Country is Required",
  STATE_REQUIRED: "State is Required",
  ALLOW_ONLY_CHARACTERS: "Allow only characters",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_MATCH: "Password Should Match",
  NUMBER_REQUIRED: "Mobile number is required",
  NUMBER_PATTERN: "The phone must be between 9 and 14 digits",
  REVIEW_TITLE_REQUIRED: "Review Title is Required",
  REVIEW_DESCRIPTION_REQUIRED: "Review Description is Required",
  REVIEW_RATING_REQUIRED: "Review Rating is Required",
  DESCRIPTION_REQUIRED: "Description is Required",
  ADDRESS_REQUIRED: "Address is required",
  METAL_COLOR_REQUIRED: "Metal Color is required",
  METAL_PURITY_REQUIRED: "Metal Purity is required",
  DIAMOND_QUALITY_REQUIRED: "Diamond Quality is required",
  SPECIAL_CHARACTERS_NOW_ALLOW:
    "Special characters or blank spaces are not allowed",
  REMARK: "Remark is required",
  COUPON_CODE_REQUIRED: "Coupon Code is required",
  NATURE_OF_ORGANIZATION_REQUIRED: "Nature of Organization is required",
  NATURE_OF_ORGANIZATION_OTHERS_REQUIRED:
    "Others Nature of Organization is required",
  GST_NUMBER_REQUIRED: "GST Number is required",
  DESIGNATION_REQUIRED: "Designation is required",
  DESIGNATION_NAME_REQUIRED: "Designation Name is required",
  IFSC_REQUIRED: "IFSC Code is required",
  ACCOUNT_NUMBER_REQUIRED: "Account Number is required",
  BANKER_NAME_REQUIRED: "Banker Name is required",
  COMPANY_NAME_REQUIRED: "Company Name is required",
  ALLOW_ONLY_NUMBER: "Allow only number",
  CONTACT_PERSON_NAME_REQUIRED: "Contact Person Name is required",
  REGISTRATION_NUMBER_REQUIRED: "Registration Number is required",
  COMPANY_WEBSITE_REQUIRED: "Company Website Name is required",
  PINCODE_REQUIRED: "PinCode/PostCode is required",
  PINCODE_REGEX_MESSAGE: "Pincode should have 5 charectors or digits",
  MESSAGE_REQUIRED: "Message is Required",
  DATE_REQUIRED: "Date is Required",
  TIME_REQUIRED: "Time is Required",
  CART_UPDATE_MESSAGE_SUCCESS: "Product is added successfully in cart",
  CART_QTY_MESSAGE_SUCCESS: "Product quantity is updated successfully",
  CART_REMOVE_MESSAGE_SUCCESS: "Item Removed From The Cart",
  CART_REMOVE_ALL_MESSAGE_SUCCESS: "All Item Has Been Removed From The Cart",
  RECIPIENT_REQUIRED: "Recipient Name is required",
  SENDER_REQUIRED: "Sender Name is required",
  METAL_REQUIRED: "Metal is required",
  DIAMOND_REQUIRED: "Diamond is required",
  OTP_REQUIRED: "OTP is required",
  OTP_LENGTH: "OTP Length Must be 6 Digit",
  COLOR_STONE_REQUIRED: "Color Stone is required",
  CURRENT_LOCATION: "Current Location is required",
  FULLNAME_REQUIRED: "Full Name is required",
  EMAILOTP_REQUIRED: "Email OTP is required",
  MOBILEOTP_REQUIRED: "Mobile OTP is required",
  NOCOUNTRY: "No countries available.",
  NOCITY: "No cities available.",
  NOSTATE: "No state available.",
  TERMS_AND_CONDITIONS_REQUIRED: "Please agree to the Terms and Conditions.",
  BLANK_SPACE_NOW_ALLOW: "Blank spaces are not allowed",
  GST_NUM_PATTERN: "Please Enter valid GST number",
  BUSINESS_NAME_REQUIRE: "Please Enter Business Name",
  INVALID_NAME: 'Invalid name',
  INQUIRY_REQUIRED: "Inquiry is Required",

  CARD_HOLDER_NAME_REQUIRED: "Cardholder name is required",
  CARD_NUMBER_REQUIRED: "Card number is required",
  INVALID_CARD_NUMBER: "Invalid card number",
  EXPIRY_MONTH_REQUIRED: "Expiry month is required",
  INVALID_EXPIRY_MONTH: "Expiry month is invalid",
  INVALID_EXPIRY_YEAR: "Expiry year is invalid",
  EXPIRY_YEAR_REQUIRED: "Expiry year is required",
  CARD_CODE_REQUIRED: "Card code is required",
  INVALID_CARD_CODE: "Invalid card code",
  INVALID_ZIP_CODE: "Invalid zip code",
  ZIP_CODE_REQUIRED: "Zip code is required",
};
