import APPCONFIG from "@config/app.config";

export const IMAGE_PATH = {
  maintenanceMode: APPCONFIG.IMAGE_PATH_URL + "maintenance.webp",
  favicon: APPCONFIG.IMAGE_PATH_URL + "favicon.ico",
  aboutUsStoryFrontWebp: APPCONFIG.IMAGE_PATH_URL + "about_us/story-front.webp",
  aboutUsStoryFrontJpg: APPCONFIG.IMAGE_PATH_URL + "about_us/story-front.jpg",
  aboutUsFounderWebp: APPCONFIG.IMAGE_PATH_URL + "about_us/founder.webp",
  aboutUsFounderJpg: APPCONFIG.IMAGE_PATH_URL + "about_us/founder.jpg",
  homeBannerWebp: APPCONFIG.IMAGE_PATH_URL + "home/home-banner.webp",
  homeBannerPng: APPCONFIG.IMAGE_PATH_URL + "home/home-banner.png",
  blogPostSevenWebp: APPCONFIG.IMAGE_PATH_URL + "blog_post7.webp",
  blogPostSevenJpg: APPCONFIG.IMAGE_PATH_URL + "blog_post7.jpg",
  blogPostEightWebp: APPCONFIG.IMAGE_PATH_URL + "blog_post8.webp",
  blogPostEightJpg: APPCONFIG.IMAGE_PATH_URL + "blog_post8.jpg",
  blogPostOneWebp: APPCONFIG.IMAGE_PATH_URL + "blog_post1.webp",
  blogPostOneJpg: APPCONFIG.IMAGE_PATH_URL + "blog_post1.jpg",
  callCenterOperatorWebp:
    APPCONFIG.IMAGE_PATH_URL + "home/callcenter-operator.webp",
  callCenterOperatorJpg:
    APPCONFIG.IMAGE_PATH_URL + "home/callcenter-operator.jpg",
  mobilePng: APPCONFIG.IMAGE_PATH_URL + "home/mobile.png",
  ringwebp: APPCONFIG.IMAGE_PATH_URL + "home/ring.webp",
  ringJpg: APPCONFIG.IMAGE_PATH_URL + "home/ring.jpg",
  earingWebp: APPCONFIG.IMAGE_PATH_URL + "home/earings.webp",
  earingJpg: APPCONFIG.IMAGE_PATH_URL + "home/earings.jpg",
  multiRingWebp: APPCONFIG.IMAGE_PATH_URL + "home/multi-ring.webp",
  multiRingJpg: APPCONFIG.IMAGE_PATH_URL + "home/multi-ring.jpg",
  setWebp: APPCONFIG.IMAGE_PATH_URL + "home/set.webp",
  setJpg: APPCONFIG.IMAGE_PATH_URL + "home/set.jpg",
  necklaceWebp: APPCONFIG.IMAGE_PATH_URL + "home/necklace.webp",
  necklaceJpg: APPCONFIG.IMAGE_PATH_URL + "home/necklace.jpg",
  namePendantWebp: APPCONFIG.IMAGE_PATH_URL + "home/name-pendant.webp",
  namePendatnJpg: APPCONFIG.IMAGE_PATH_URL + "home/name-pendant.jpg",
  antiquePendantWebp: APPCONFIG.IMAGE_PATH_URL + "home/antique-pendant.webp",
  antiquePeendantJpg: APPCONFIG.IMAGE_PATH_URL + "home/antique-pendant.jpg",
  diamondWebp: APPCONFIG.IMAGE_PATH_URL + "home/diamond.webp",
  diamondJpg: APPCONFIG.IMAGE_PATH_URL + "home/diamond.jpg",
  testimonialImgMinifiedWebp:
    APPCONFIG.IMAGE_PATH_URL + "testimonial_img_minified.webp",
  testimonialImgMinifiedPng:
    APPCONFIG.IMAGE_PATH_URL + "testimonial_img_minified.png",
  markerIcon: APPCONFIG.IMAGE_PATH_URL + "map-marker.svg",
  productBannerJpg: APPCONFIG.IMAGE_PATH_URL + "contactuse_banner.jpg",
  noImagePng: APPCONFIG.IMAGE_PATH_URL + "no-image.png",
  notFoundPageWebp: APPCONFIG.IMAGE_PATH_URL + "404/404.webp",
  noRecordsJpg: APPCONFIG.IMAGE_PATH_URL + "no-records/no-records.jpg",
  noRecordsWebp: APPCONFIG.IMAGE_PATH_URL + "no-records/no-records.webp",
  contactUsBanner: APPCONFIG.IMAGE_PATH_URL + "contactuse_banner.jpg",
  userProfile: APPCONFIG.IMAGE_PATH_URL + "default-avatar.png",
  confirmationImg: APPCONFIG.IMAGE_PATH_URL + "confirmation_image.jpg",
  confirmationImgWeb: APPCONFIG.IMAGE_PATH_URL + "confirmation_image.webp",
  offerImageWeb: APPCONFIG.IMAGE_PATH_URL + "offers/pop-up-offer.webp",
  offerImageJpg: APPCONFIG.IMAGE_PATH_URL + "offers/pop-up-offer.jpg",
  NotFoundPng: APPCONFIG.IMAGE_PATH_URL + "404/404.png",
  checkoutRing : APPCONFIG.IMAGE_PATH_URL + "recently_viewed/ring.jpg",
  ccAvanue : APPCONFIG.IMAGE_PATH_URL + "ccavenue.webp",
  razorPay: APPCONFIG.IMAGE_PATH_URL + "razorpay.webp",
  stripe: APPCONFIG.IMAGE_PATH_URL + "stripe.webp"
};
