export const WhatsAppActionTypes = {
    SET_WHATSAPP_NUMBER: "SET_WHATSAPP_NUMBER",
    SET_GENERAL_CONF_NUMBER: "SET_GENERAL_CONF_NUMBER",
    SET_GENERAL_CONF_COUNTRY: "SET_GENERAL_CONF_COUNTRY",
    SET_WHATSAPP_FEED: "SET_WHATSAPP_FEED",
}