import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useCallback } from "react";
import useRazorpay from "react-razorpay";

export default function Home() {
  const Razorpay = useRazorpay();

  const handlePayment = useCallback(
    (paymentResponse: any) => {
      const { order_id, amount } = paymentResponse;
      const options = {
        key: "YOUR_RAZOR_PAYMENT_KEY",
        amount: amount,
        currency: "INR",
        name: "Cart Checkout",
        image: "/indian.jpg",
        order_id: order_id,
        prefill: {
          name: `Akash Sanariya`,
          contact: `+91-79-41054646`,
          email: `akash.sanariya@brainvire.com`,
        },
        handler: (res: any) => {
          if (res) {
            console.log("Success Response", res);
          }
        },
        theme: {
          color: "#3399cc",
        },
      };
      const rzpay = new Razorpay(options);
      rzpay.on("payment.failed", function (response: any) {
        console.log("Failed Response", response);
      });
      rzpay.on("payment.cancel", function (response: any) {
        console.log("Cancel Response", response);
      });
      rzpay.open();
    },
    [Razorpay]
  );

  const placeOrder = () => {
    handlePayment({
      order_id: "order_9A33XWu170gUtm",
      amount: 200,
    });
  };

  return (
    <>
      <Head>
        <title>Next Js Razorpay App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.card}>
          <Image
            width={50}
            height={50}
            alt="Indian Army Logo"
            src={"/indian.jpg"}
          />
          <h1>Indian Army</h1>
          <p className={styles.price}>₹ 200</p>
          <p>Indian Army exists with values such as Spirit of Selfless Sacrifice, Valour, Discipline and Integrity. The Logo of the Indian Army depicts two swords in cross below the National Emblem of India. The National Emblem and swords are in the yellow shade with the background in the shade of red.</p>
          <p>
            <button onClick={() => placeOrder()}>Buy Now</button>
          </p>
        </div>
      </main>
    </>
  );
}
