// All modules error messages
export const Message = {
  SOMETHING_WENT_WRONG: "Something Went Wrong!",
  EMAIL_REQUIRED: "Email is Required",
  DUPLICATE_EMAIL_REQUIRED: 'Duplicate email ids are not allowed',
  EMAIL_PATTERN: "Invalid Email Address. E.g. example@email.com",
  PASSWORD_PATTERN:
    "Password must contain 1 upper case, 1 lower case, 1 number, 1 special character ( @ ! $ % ^ & #) & minimum 8 characters to maximum 40 characters",
  MOBILE_PATTERN: "Invalid Mobile Number.",
  MOBILE_AND_COURT_CODE: "Country Code and Mobile Number are Required",
  MOBILE_NUMBER_REQUIRED: "Mobile Number is Required",
  NAME_REQUIRED: "Name is Required",
  FIRST_NAME_REQUIRED: "First Name is Required",
  LAST_NAME_REQUIRED: "Last Name is Required",
  FIRST_NAME_PATTERN: "First name special characters and numbers not allowed",
  LAST_NAME_PATTERN: "Last name special characters and numbers not allowed",
  GENDER_REQUIRED: "Gender is Required",
  CITY_REQUIRED: "City is Required",
  WHITE_SPACE: " Whitespace not allowed at the beginning and at the end.",
  COUNTRY_REQUIRED: "Country Code is Required",
  STATE_REQUIRED: "State is Required",
  ALLOW_ONLY_CHARACTERS: "Enter Only Characters No Space Allowed",
  NEW_PASSWORD_REQUIRED: "New Password is Required",
  PASSWORD_REQUIRED: "Password is Required",
  CURRENT_PASSWORD_REQUIRED: "Current Password is Required",
  CONFIRM_PASSWORD_REQUIRED: "Confirm Password is Required",
  PASSWORD_MATCH: "Password Should Match",
  NUMBER_REQUIRED: "Mobile number is required",
  NUMBER_PATTERN: "The phone must be between 9 and 14 digits",
  REVIEW_TITLE_REQUIRED: "Review Title is Required",
  REVIEW_DESCRIPTION_REQUIRED: "Review Description is Required",
  REVIEW_RATING_REQUIRED: "Review Rating is Required",
  DESCRIPTION_REQUIRED: "Description is Required!",
  ADDRESS_REQUIRED: "Address is required",
  METAL_COLOR_REQUIRED: "Metal Color is required",
  METAL_PURITY_REQUIRED: "Metal Purity is required",
  DIAMOND_QUALITY_REQUIRED: "Diamond Quality is required",
  SPECIAL_CHARACTERS_NOW_ALLOW:
    "Special characters or blank spaces are not allowed",
  REMARK: "Remark is required",
  COUPON_CODE_REQUIRED: "Coupon Code is required",
  NATURE_OF_ORGANIZATION_REQUIRED: "Nature of Organization is required",
  NATURE_OF_ORGANIZATION_OTHERS_REQUIRED:
    "Others Nature of Organization is required",
  GST_NUMBER_REQUIRED: "GST Number is required",
  DESIGNATION_REQUIRED: "Designation is required",
  DESIGNATION_NAME_REQUIRED: "Designation Name is required",
  IFSC_REQUIRED: "IFSC Code is required",
  ACCOUNT_NUMBER_REQUIRED: "Account Number is required",
  BANKER_NAME_REQUIRED: "Banker Name is required",
  COMPANY_NAME_REQUIRED: "Company Name is required",
  ALLOW_ONLY_NUMBER: "enter only numbers",
  CONTACT_PERSON_NAME_REQUIRED: "Contact Person Name is required",
  REGISTRATION_NUMBER_REQUIRED: "Registration Number is required",
  COMPANY_WEBSITE_REQUIRED: "Company Website Name is required",
  MESSAGE_REQUIRED: "Message is Required",
  DATE_REQUIRED: "Date is Required",
  TIME_REQUIRED: "Time is Required",
  TIME_PATTERN: "Selected time can't be earlier than the current time",
  DATE_PATTERN: "Selected date can't be earlier than the current date",
  CART_UPDATE_MESSAGE_SUCCESS: "Product is added successfully in cart",
  CART_QTY_MESSAGE_SUCCESS: "Product quantity is updated successfully",
  CART_REMOVE_MESSAGE_SUCCESS: "Item Removed From The Cart",
  CART_REMOVE_ALL_MESSAGE_SUCCESS: "All Item Has Been Removed From The Cart",
  RECIPIENT_REQUIRED: "Recipient Name is required",
  SENDER_REQUIRED: "Sender Name is required",
  METAL_REQUIRED: "Metal is required",
  DIAMOND_REQUIRED: "Diamond is required",
  OTP_REQUIRED: "OTP is required",
  OTP_LENGTH: "OTP Length Must be 6 Digit",
  COLOR_STONE_REQUIRED: "Color Stone is required",
  CURRENT_LOCATION: "Current Location is required",
  TERMS_AND_CONDITIONS_REQUIRED: "Please agree to the Terms and Conditions.",
  BLANK_SPACE_NOW_ALLOW: "Blank spaces are not allowed",
  GST_NUM_PATTERN: "Please Enter valid GST number",
  BUSINESS_NAME_REQUIRE: "Please Enter Business Name",
  INVALID_NAME: 'Invalid name',
  INQUIRY_REQUIRED: "Inquiry is Required",

  CARD_HOLDER_NAME_REQUIRED: "Cardholder name is required",
  CARD_NUMBER_REQUIRED: "Card number is required",
  INVALID_CARD_NUMBER: "Invalid card number",
  EXPIRY_MONTH_REQUIRED: "Expiry month is required",
  INVALID_EXPIRY_MONTH: "Expiry month is invalid",
  INVALID_EXPIRY_YEAR: "Expiry year is invalid",
  EXPIRY_YEAR_REQUIRED: "Expiry year is required",
  CARD_CODE_REQUIRED: "Card code is required",
  INVALID_CARD_CODE: "Invalid card code",
  INVALID_ZIP_CODE: "Invalid zip code",
  ZIP_CODE_REQUIRED: "Zip code is required",
  COUNTRY_CODE_REQUIRED: 'Please Select Country Code!',
  TERMS_AND_CONDITIONS_REQUIRED_TOAST: 'Please Accept Terms And Conditions!',

  CAPTCHA_REQUIRED: 'Please verify captcha!',
  IMAGES_REQUIRED: 'Image URL is Required!',
  INVALID_IMAGES: 'Please enter valid image URL. URL should start with "https://" or "http://',
  INVALID_PRODUCT_URL: 'Please enter valid product URL. URL should start with "https://" or "http://',
  SKU_REQUIRED: 'Product SKU is Required!',
  URL_REQUIRED: 'Product URL is Required!',
  COLOR_REQUIRED: 'Color is Required!',
  SIZE_REQUIRED: 'Size is Required!',
  PRICE_REQUIRED: 'Price is Required!',
  PRODUCT_DESCRIPTION: 'Product Description is Required!',
  SOMETHING_WENT_WRONG_TRY_AGAIN: 'Failed, something went wrong, try again!',
  STEP_1_REQUIRED: "Please complete step 1 to proceed.",
  STEP_2_REQUIRED: "Please complete step 2 to proceed.",
  STEP_3_REQUIRED: "Please complete step 3 to proceed.",

  STREAM_TITLE_REQUIRED: 'Stream title is required!',
  STREAM_DESCRIPTION_REQUIRED: 'Stream description is required!',
  PRODUCT_REQUIRED: 'Product is Required!',
  PAGE_REQUIRED: 'Page is required!',
  FACEBOOK_NOT_CONNECTED: 'Facebook page is not connected yet, go to my account section!',
  INSTA_NOT_CONNECTED: 'Instagram account is not connected with your facebook yet!',
  FACEBOOK_REQUIRED: 'Please connect to any broadcast channel!',
  BRAND_NAME: 'Domain Name is Required',
  COMPANY_NAME: 'Company Name is Required',
  BRAND_NAME_PATTERN: 'Domain name special characters and uppercase letter are not allowed.',
  BRAND_REPRESENTATIVE: 'Brand Representative Required!',
  BRAND_EMAIL: 'Brand Email is Required',
  INFLUENCER_COUNT: 'Influencer Count is Required',
  SESSION_COUNT: 'Session Count is Required',
  NUMBERS: 'only numbers allowed',
  TERMS_CONDITIONS: 'terms and conditions required',
  KEYWORD_COUNT: "keyword Count is Required",
  KEYWORDS: "Keyword is Required",
  CURRENT_STREAMING_END : "You cannot go live until your current streaming ends",
  CAMERA_MICROPHONE_NOT_SUPPORTED:'Error accessing camera and microphone, Camera or Microphone not supported.',

  SESSION_EXPIRED: 'Streaming Session expired',
  INVALID_SESSION: 'Session is invalid',
  FAILED_TO_SEND_INVITATION: 'Failed to send invitation',

  INSTAGRAM_ID_REQUIRED: 'Instagram id is Required',
  INSTA_SESSION_EXPIRED: 'Instagram session expired',
  STREAMING_KEY_REQUIRED: 'Streaming key is Required!',
  STREAMING_URL_REQUIRED: 'Streaming url is Required!',
  CONFIRM_CATALOGS_TO_DELETE: "Are you sure you want to delete product's?",
  PRODUCTS_NOT_SELECTED_FOR_DELETE: 'Please select products to delete',
  CONFIRM_DELETE: 'Are you sure you want to delete product?',


  SCHEDULE_DATE_REQUIRED: 'Schedule date is required!',
  SCHEDULE_TIME_REQUIRED: 'Schedule time is required!',
  TIME_ZONE_REQUIRED: 'Time zone is required!',
  CONFIRM_DELETE_SCHEDULE_STREAM: 'Are you sure you want to delete schedule streaming?',


  CONFIRM_INFUE_TO_DELETE: "Are you sure you want to delete selected influencer's?",
  INFLUE_NOT_SELECTED_FOR_DELETE: 'Please select influencer to delete',
  CONFIRM_DELETE_INFLUE: 'Are you sure you want to delete influencer?',
  INFLUENCER_REQUIRED: 'Influencer is required!',
  BRAND_PRODUCT_NOT_FOUND: 'Brand product not found!',
  ALLOW400CHAR: 'Allowed max 400 characters',
  ALLOW200CHAR: 'Allowed max 200 characters',
  ALLOW50CHAR: 'Allowed max 50 characters',
  MAX_LENGTH_3: 'Allowed max 3 digits',
  ALLOW6CHAR: 'Allowed max 6 characters',
  FAILED_TO_PREPARE_STREAM: 'Failed to prepare streaming, try again after some time',
  FILED_TO_START_STREAM: 'Failed to start streaming, getting issue with your selected product image',
  FAILED_TO_UPDATE_STREAM: 'Failed to update streaming product, getting issue with your selected product image, Try again',
  IMG_DOMAIN_RESTRICTED: 'This domain has restricted image for cross origin. Please try from other source',
  FAILED_TO_UPDATE_PRODUCT: 'Failed to update streaming product, Try again',
  STREAMING_PRODUCT_UPDATED: 'Streaming product updated successfully.',
  SESSION_EXPIRED_TOAST: 'Session expired!',
  FILE_NOT_UPLOADED: "File not uploaded",
  INFLUENCER_EXIST: "Influencer Already Exist",
  UPLOAD_VALID_CSV: "Please upload a valid CSV file.",
  THEME_COLOR_NOT_CHANGE: 'Theme color not updated. Please try again later.',

  YOUTUBE_LOGIN_FAILED: 'Google signed in failed, please try again later',
  YOUTUBE_POPUP_BLOCKED: 'Failed to open popup window,Please allow popup for site and try again.',
  YOUTUBE_NOT_CONNECTED:  'Youtube channel is not connected yet, go to my account section!',
  YOUTUBE_CONNECTED_SUCCESS: 'Youtube channel connected successfully.',
  CLIENT_ID_REQUIRED: 'The client id is required.',
  INVALID_CLIENT_ID: 'The client id seems invalid.',
  VALID_SCOPE_REQUIRED: 'A valid scope array is required.',
  SCOPE_INVALID: 'Invalid scopes',
  SOME_SCOPE_INVALID: 'Some scopes are invalid.',

 TIKTOK_LOGIN_FAILED: 'TikTok signed in failed, please try again later',
 TIKTOK_NOT_CONNECTED:  'TikTok not connected yet, go to my account section!',
 TIKTOK_CONNECTED_SUCCESS: 'TikTok connected successfully.',

  LINKEDIN_CONNECTED_SUCCESS: 'Linkedin connected successfully.',
  LINKEDIN_LOGIN_FAILED: 'Linkedin signed in failed, please try again later',
  LINKEDIN_NOT_CONNECTED:  'Linkedin page is not connected yet, go to my account section!',

  FAILED_TO_SWITCH_CAMERA: 'Failed to switch video device.'
};
